# Generated by Django 4.2.7 on 2023-12-05 04:10

import desks.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Image for desk', null=True, upload_to=functools.partial(desks.models.wrapper, *(), **{'target': 'desk'}), verbose_name='Image desk')),
                ('name', models.CharField(help_text='Name of desk', max_length=100, unique=True, verbose_name='Name desk')),
                ('description', models.TextField(help_text='Describe information about desk', null=True, verbose_name='Desk Description')),
            ],
            options={
                'db_table': 'desks',
            },
        ),
    ]
