# Generated by Django 4.2.7 on 2023-12-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_is_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_front',
        ),
    ]
